package maping;
// Generated 23/10/2014 05:20:25 PM by Hibernate Tools 3.6.0



/**
 * Anios generated by hbm2java
 */
public class Anios  implements java.io.Serializable {


     private long idanios;
     private String anio;

    public Anios() {
    }

	
    public Anios(long idanios) {
        this.idanios = idanios;
    }
    public Anios(long idanios, String anio) {
       this.idanios = idanios;
       this.anio = anio;
    }
   
    public long getIdanios() {
        return this.idanios;
    }
    
    public void setIdanios(long idanios) {
        this.idanios = idanios;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }




}


