package maping;
// Generated 23/10/2014 05:20:25 PM by Hibernate Tools 3.6.0



/**
 * DetallOficcirc generated by hbm2java
 */
public class DetallOficcirc  implements java.io.Serializable {


     private DetallOficcircId id;
     private OficCirc oficCirc;
     private Dependencia dependencia;

    public DetallOficcirc() {
    }

	
    public DetallOficcirc(DetallOficcircId id) {
        this.id = id;
    }
    public DetallOficcirc(DetallOficcircId id, OficCirc oficCirc, Dependencia dependencia) {
       this.id = id;
       this.oficCirc = oficCirc;
       this.dependencia = dependencia;
    }
   
    public DetallOficcircId getId() {
        return this.id;
    }
    
    public void setId(DetallOficcircId id) {
        this.id = id;
    }
    public OficCirc getOficCirc() {
        return this.oficCirc;
    }
    
    public void setOficCirc(OficCirc oficCirc) {
        this.oficCirc = oficCirc;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }




}


