package maping;
// Generated 20/10/2014 11:41:07 AM by Hibernate Tools 3.6.0



/**
 * DetallOficcircId generated by hbm2java
 */
public class DetallOficcircId  implements java.io.Serializable {


     private Long idOfcirc;
     private Long codigo;

    public DetallOficcircId() {
    }

    public DetallOficcircId(Long idOfcirc, Long codigo) {
       this.idOfcirc = idOfcirc;
       this.codigo = codigo;
    }
   
    public Long getIdOfcirc() {
        return this.idOfcirc;
    }
    
    public void setIdOfcirc(Long idOfcirc) {
        this.idOfcirc = idOfcirc;
    }
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallOficcircId) ) return false;
		 DetallOficcircId castOther = ( DetallOficcircId ) other; 
         
		 return ( (this.getIdOfcirc()==castOther.getIdOfcirc()) || ( this.getIdOfcirc()!=null && castOther.getIdOfcirc()!=null && this.getIdOfcirc().equals(castOther.getIdOfcirc()) ) )
 && ( (this.getCodigo()==castOther.getCodigo()) || ( this.getCodigo()!=null && castOther.getCodigo()!=null && this.getCodigo().equals(castOther.getCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdOfcirc() == null ? 0 : this.getIdOfcirc().hashCode() );
         result = 37 * result + ( getCodigo() == null ? 0 : this.getCodigo().hashCode() );
         return result;
   }   


}


