package maping;
// Generated 05/11/2014 09:54:41 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * DetallOficcirc generated by hbm2java
 */
public class DetallOficcirc  implements java.io.Serializable {


     private BigDecimal idDetalloficirc;
     private OficCirc oficCirc;
     private TiposDocumentos tiposDocumentos;
     private Dependencia dependencia;

    public DetallOficcirc() {
    }

	
    public DetallOficcirc(BigDecimal idDetalloficirc) {
        this.idDetalloficirc = idDetalloficirc;
    }
    public DetallOficcirc(BigDecimal idDetalloficirc, OficCirc oficCirc, TiposDocumentos tiposDocumentos, Dependencia dependencia) {
       this.idDetalloficirc = idDetalloficirc;
       this.oficCirc = oficCirc;
       this.tiposDocumentos = tiposDocumentos;
       this.dependencia = dependencia;
    }
   
    public BigDecimal getIdDetalloficirc() {
        return this.idDetalloficirc;
    }
    
    public void setIdDetalloficirc(BigDecimal idDetalloficirc) {
        this.idDetalloficirc = idDetalloficirc;
    }
    public OficCirc getOficCirc() {
        return this.oficCirc;
    }
    
    public void setOficCirc(OficCirc oficCirc) {
        this.oficCirc = oficCirc;
    }
    public TiposDocumentos getTiposDocumentos() {
        return this.tiposDocumentos;
    }
    
    public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
        this.tiposDocumentos = tiposDocumentos;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }




}


