package maping;
// Generated 30/09/2014 04:09:18 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DocusExtint generated by hbm2java
 */
public class DocusExtint  implements java.io.Serializable {


     private long id;
     private String numerodoc;
     private String asunto;
     private Date fecha;
     private String observacion;

    public DocusExtint() {
    }

	
    public DocusExtint(long id, Date fecha) {
        this.id = id;
        this.fecha = fecha;
    }
    public DocusExtint(long id, String numerodoc, String asunto, Date fecha, String observacion) {
       this.id = id;
       this.numerodoc = numerodoc;
       this.asunto = asunto;
       this.fecha = fecha;
       this.observacion = observacion;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNumerodoc() {
        return this.numerodoc;
    }
    
    public void setNumerodoc(String numerodoc) {
        this.numerodoc = numerodoc;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


