package maping;
// Generated 15/12/2014 11:44:57 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DocumentosOfiint generated by hbm2java
 */
public class DocumentosOfiint  implements java.io.Serializable {


     private long idDocofint;
     private TiposDocumentos tiposDocumentos;
     private Dependencia dependenciaByCodigo1;
     private Usuario usuario;
     private Dependencia dependenciaByCodigo;
     private String correlativoDocofint;
     private String asunto;
     private Date fecha;
     private String siglas;

    public DocumentosOfiint() {
    }

	
    public DocumentosOfiint(long idDocofint) {
        this.idDocofint = idDocofint;
    }
    public DocumentosOfiint(long idDocofint, TiposDocumentos tiposDocumentos, Dependencia dependenciaByCodigo1, Usuario usuario, Dependencia dependenciaByCodigo, String correlativoDocofint, String asunto, Date fecha, String siglas) {
       this.idDocofint = idDocofint;
       this.tiposDocumentos = tiposDocumentos;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.usuario = usuario;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.correlativoDocofint = correlativoDocofint;
       this.asunto = asunto;
       this.fecha = fecha;
       this.siglas = siglas;
    }
   
    public long getIdDocofint() {
        return this.idDocofint;
    }
    
    public void setIdDocofint(long idDocofint) {
        this.idDocofint = idDocofint;
    }
    public TiposDocumentos getTiposDocumentos() {
        return this.tiposDocumentos;
    }
    
    public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
        this.tiposDocumentos = tiposDocumentos;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public String getCorrelativoDocofint() {
        return this.correlativoDocofint;
    }
    
    public void setCorrelativoDocofint(String correlativoDocofint) {
        this.correlativoDocofint = correlativoDocofint;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getSiglas() {
        return this.siglas;
    }
    
    public void setSiglas(String siglas) {
        this.siglas = siglas;
    }




}


