package maping;
// Generated 06/10/2014 08:55:07 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DocusExt generated by hbm2java
 */
public class DocusExt  implements java.io.Serializable {


     private long iddoc;
     private String nombdocu;
     private Set<DocusExtint> docusExtints = new HashSet<DocusExtint>(0);

    public DocusExt() {
    }

	
    public DocusExt(long iddoc) {
        this.iddoc = iddoc;
    }
    public DocusExt(long iddoc, String nombdocu, Set<DocusExtint> docusExtints) {
       this.iddoc = iddoc;
       this.nombdocu = nombdocu;
       this.docusExtints = docusExtints;
    }
   
    public long getIddoc() {
        return this.iddoc;
    }
    
    public void setIddoc(long iddoc) {
        this.iddoc = iddoc;
    }
    public String getNombdocu() {
        return this.nombdocu;
    }
    
    public void setNombdocu(String nombdocu) {
        this.nombdocu = nombdocu;
    }
    public Set<DocusExtint> getDocusExtints() {
        return this.docusExtints;
    }
    
    public void setDocusExtints(Set<DocusExtint> docusExtints) {
        this.docusExtints = docusExtints;
    }




}


