package maping;
// Generated 02/10/2014 12:28:57 PM by Hibernate Tools 3.6.0



/**
 * DocusExt generated by hbm2java
 */
public class DocusExt  implements java.io.Serializable {


     private long iddoc;
     private String nombdocu;

    public DocusExt() {
    }

	
    public DocusExt(long iddoc) {
        this.iddoc = iddoc;
    }
    public DocusExt(long iddoc, String nombdocu) {
       this.iddoc = iddoc;
       this.nombdocu = nombdocu;
    }
   
    public long getIddoc() {
        return this.iddoc;
    }
    
    public void setIddoc(long iddoc) {
        this.iddoc = iddoc;
    }
    public String getNombdocu() {
        return this.nombdocu;
    }
    
    public void setNombdocu(String nombdocu) {
        this.nombdocu = nombdocu;
    }




}


