package maping;
// Generated 23/10/2014 05:20:25 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocusExtint generated by hbm2java
 */
public class DocusExtint  implements java.io.Serializable {


     private long id;
     private Dependencia dependenciaByCodigo1;
     private Usuario usuario;
     private Dependencia dependenciaByCodigo;
     private DocusExt docusExt;
     private String numerodoc;
     private String asunto;
     private Date fecha;
     private Long movimientoDext;
     private Set<Proveido> proveidos = new HashSet<Proveido>(0);

    public DocusExtint() {
    }

	
    public DocusExtint(long id) {
        this.id = id;
    }
    public DocusExtint(long id, Dependencia dependenciaByCodigo1, Usuario usuario, Dependencia dependenciaByCodigo, DocusExt docusExt, String numerodoc, String asunto, Date fecha, Long movimientoDext, Set<Proveido> proveidos) {
       this.id = id;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.usuario = usuario;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.docusExt = docusExt;
       this.numerodoc = numerodoc;
       this.asunto = asunto;
       this.fecha = fecha;
       this.movimientoDext = movimientoDext;
       this.proveidos = proveidos;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public DocusExt getDocusExt() {
        return this.docusExt;
    }
    
    public void setDocusExt(DocusExt docusExt) {
        this.docusExt = docusExt;
    }
    public String getNumerodoc() {
        return this.numerodoc;
    }
    
    public void setNumerodoc(String numerodoc) {
        this.numerodoc = numerodoc;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Long getMovimientoDext() {
        return this.movimientoDext;
    }
    
    public void setMovimientoDext(Long movimientoDext) {
        this.movimientoDext = movimientoDext;
    }
    public Set<Proveido> getProveidos() {
        return this.proveidos;
    }
    
    public void setProveidos(Set<Proveido> proveidos) {
        this.proveidos = proveidos;
    }




}


