package maping;
// Generated 17/04/2015 04:53:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DocusExtint generated by hbm2java
 */
public class DocusExtint  implements java.io.Serializable {


     private long id;
     private TiposDocumentos tiposDocumentos;
     private Dependencia dependenciaByCodigo1;
     private Usuario usuario;
     private Dependencia dependenciaByCodigo;
     private String numerodoc;
     private String asunto;
     private Date fecha;
     private Long movimientoDext;
     private String correlativod;
     private Date fechaEnvio;
     private String extInt;
     private Date fechaDerivado;

    public DocusExtint() {
    }

	
    public DocusExtint(long id) {
        this.id = id;
    }
    public DocusExtint(long id, TiposDocumentos tiposDocumentos, Dependencia dependenciaByCodigo1, Usuario usuario, Dependencia dependenciaByCodigo, String numerodoc, String asunto, Date fecha, Long movimientoDext, String correlativod, Date fechaEnvio, String extInt, Date fechaDerivado) {
       this.id = id;
       this.tiposDocumentos = tiposDocumentos;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.usuario = usuario;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.numerodoc = numerodoc;
       this.asunto = asunto;
       this.fecha = fecha;
       this.movimientoDext = movimientoDext;
       this.correlativod = correlativod;
       this.fechaEnvio = fechaEnvio;
       this.extInt = extInt;
       this.fechaDerivado = fechaDerivado;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public TiposDocumentos getTiposDocumentos() {
        return this.tiposDocumentos;
    }
    
    public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
        this.tiposDocumentos = tiposDocumentos;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public String getNumerodoc() {
        return this.numerodoc;
    }
    
    public void setNumerodoc(String numerodoc) {
        this.numerodoc = numerodoc;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Long getMovimientoDext() {
        return this.movimientoDext;
    }
    
    public void setMovimientoDext(Long movimientoDext) {
        this.movimientoDext = movimientoDext;
    }
    public String getCorrelativod() {
        return this.correlativod;
    }
    
    public void setCorrelativod(String correlativod) {
        this.correlativod = correlativod;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public String getExtInt() {
        return this.extInt;
    }
    
    public void setExtInt(String extInt) {
        this.extInt = extInt;
    }
    public Date getFechaDerivado() {
        return this.fechaDerivado;
    }
    
    public void setFechaDerivado(Date fechaDerivado) {
        this.fechaDerivado = fechaDerivado;
    }




}


