package maping;
// Generated 17/04/2015 04:53:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DocusInternos generated by hbm2java
 */
public class DocusInternos  implements java.io.Serializable {


     private int idtip;
     private TiposDocumentos tiposDocumentos;
     private TramiteDatos tramiteDatos;
     private Dependencia dependenciaByCodigo1;
     private Usuario usuarioByUsu;
     private Dependencia dependenciaByCodigo;
     private Usuario usuarioByUsu1;
     private String docuCorrelaint;
     private String docuPricint;
     private String docuNombreint;
     private String docuSiglasint;
     private String docuAnioint;
     private Date fecharegistro;
     private String docuAsunto;
     private String numeroMovi;
     private String estado;

    public DocusInternos() {
    }

	
    public DocusInternos(int idtip, String docuCorrelaint, String docuPricint, String docuNombreint) {
        this.idtip = idtip;
        this.docuCorrelaint = docuCorrelaint;
        this.docuPricint = docuPricint;
        this.docuNombreint = docuNombreint;
    }
    public DocusInternos(int idtip, TiposDocumentos tiposDocumentos, TramiteDatos tramiteDatos, Dependencia dependenciaByCodigo1, Usuario usuarioByUsu, Dependencia dependenciaByCodigo, Usuario usuarioByUsu1, String docuCorrelaint, String docuPricint, String docuNombreint, String docuSiglasint, String docuAnioint, Date fecharegistro, String docuAsunto, String numeroMovi, String estado) {
       this.idtip = idtip;
       this.tiposDocumentos = tiposDocumentos;
       this.tramiteDatos = tramiteDatos;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.usuarioByUsu = usuarioByUsu;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.usuarioByUsu1 = usuarioByUsu1;
       this.docuCorrelaint = docuCorrelaint;
       this.docuPricint = docuPricint;
       this.docuNombreint = docuNombreint;
       this.docuSiglasint = docuSiglasint;
       this.docuAnioint = docuAnioint;
       this.fecharegistro = fecharegistro;
       this.docuAsunto = docuAsunto;
       this.numeroMovi = numeroMovi;
       this.estado = estado;
    }
   
    public int getIdtip() {
        return this.idtip;
    }
    
    public void setIdtip(int idtip) {
        this.idtip = idtip;
    }
    public TiposDocumentos getTiposDocumentos() {
        return this.tiposDocumentos;
    }
    
    public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
        this.tiposDocumentos = tiposDocumentos;
    }
    public TramiteDatos getTramiteDatos() {
        return this.tramiteDatos;
    }
    
    public void setTramiteDatos(TramiteDatos tramiteDatos) {
        this.tramiteDatos = tramiteDatos;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public Usuario getUsuarioByUsu() {
        return this.usuarioByUsu;
    }
    
    public void setUsuarioByUsu(Usuario usuarioByUsu) {
        this.usuarioByUsu = usuarioByUsu;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public Usuario getUsuarioByUsu1() {
        return this.usuarioByUsu1;
    }
    
    public void setUsuarioByUsu1(Usuario usuarioByUsu1) {
        this.usuarioByUsu1 = usuarioByUsu1;
    }
    public String getDocuCorrelaint() {
        return this.docuCorrelaint;
    }
    
    public void setDocuCorrelaint(String docuCorrelaint) {
        this.docuCorrelaint = docuCorrelaint;
    }
    public String getDocuPricint() {
        return this.docuPricint;
    }
    
    public void setDocuPricint(String docuPricint) {
        this.docuPricint = docuPricint;
    }
    public String getDocuNombreint() {
        return this.docuNombreint;
    }
    
    public void setDocuNombreint(String docuNombreint) {
        this.docuNombreint = docuNombreint;
    }
    public String getDocuSiglasint() {
        return this.docuSiglasint;
    }
    
    public void setDocuSiglasint(String docuSiglasint) {
        this.docuSiglasint = docuSiglasint;
    }
    public String getDocuAnioint() {
        return this.docuAnioint;
    }
    
    public void setDocuAnioint(String docuAnioint) {
        this.docuAnioint = docuAnioint;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public String getDocuAsunto() {
        return this.docuAsunto;
    }
    
    public void setDocuAsunto(String docuAsunto) {
        this.docuAsunto = docuAsunto;
    }
    public String getNumeroMovi() {
        return this.numeroMovi;
    }
    
    public void setNumeroMovi(String numeroMovi) {
        this.numeroMovi = numeroMovi;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


