package maping;
// Generated 02/09/2014 12:28:10 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Indicador generated by hbm2java
 */
public class Indicador  implements java.io.Serializable {


     private int indiCod;
     private String indiNombre;
     private Set<TramiteMovimiento> tramiteMovimientos = new HashSet<TramiteMovimiento>(0);

    public Indicador() {
    }

	
    public Indicador(int indiCod) {
        this.indiCod = indiCod;
    }
    public Indicador(int indiCod, String indiNombre, Set<TramiteMovimiento> tramiteMovimientos) {
       this.indiCod = indiCod;
       this.indiNombre = indiNombre;
       this.tramiteMovimientos = tramiteMovimientos;
    }
   
    public int getIndiCod() {
        return this.indiCod;
    }
    
    public void setIndiCod(int indiCod) {
        this.indiCod = indiCod;
    }
    public String getIndiNombre() {
        return this.indiNombre;
    }
    
    public void setIndiNombre(String indiNombre) {
        this.indiNombre = indiNombre;
    }
    public Set<TramiteMovimiento> getTramiteMovimientos() {
        return this.tramiteMovimientos;
    }
    
    public void setTramiteMovimientos(Set<TramiteMovimiento> tramiteMovimientos) {
        this.tramiteMovimientos = tramiteMovimientos;
    }




}


