package maping;
// Generated 30/09/2014 04:09:18 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Indicador generated by hbm2java
 */
public class Indicador  implements java.io.Serializable {


     private int indiCod;
     private String indiNombre;
     private Set<TramiteMovimiento> tramiteMovimientos = new HashSet<TramiteMovimiento>(0);
     private Set<MovimientoInterno> movimientoInternos = new HashSet<MovimientoInterno>(0);

    public Indicador() {
    }

	
    public Indicador(int indiCod) {
        this.indiCod = indiCod;
    }
    public Indicador(int indiCod, String indiNombre, Set<TramiteMovimiento> tramiteMovimientos, Set<MovimientoInterno> movimientoInternos) {
       this.indiCod = indiCod;
       this.indiNombre = indiNombre;
       this.tramiteMovimientos = tramiteMovimientos;
       this.movimientoInternos = movimientoInternos;
    }
   
    public int getIndiCod() {
        return this.indiCod;
    }
    
    public void setIndiCod(int indiCod) {
        this.indiCod = indiCod;
    }
    public String getIndiNombre() {
        return this.indiNombre;
    }
    
    public void setIndiNombre(String indiNombre) {
        this.indiNombre = indiNombre;
    }
    public Set<TramiteMovimiento> getTramiteMovimientos() {
        return this.tramiteMovimientos;
    }
    
    public void setTramiteMovimientos(Set<TramiteMovimiento> tramiteMovimientos) {
        this.tramiteMovimientos = tramiteMovimientos;
    }
    public Set<MovimientoInterno> getMovimientoInternos() {
        return this.movimientoInternos;
    }
    
    public void setMovimientoInternos(Set<MovimientoInterno> movimientoInternos) {
        this.movimientoInternos = movimientoInternos;
    }




}


