package maping;
// Generated 06/10/2014 08:55:07 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Jefatura generated by hbm2java
 */
public class Jefatura  implements java.io.Serializable {


     private BigDecimal idJefatura;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private String grado;
     private String dni;
     private String profesion;

    public Jefatura() {
    }

	
    public Jefatura(BigDecimal idJefatura) {
        this.idJefatura = idJefatura;
    }
    public Jefatura(BigDecimal idJefatura, Usuario usuario, String nombre, String apellido, String grado, String dni, String profesion) {
       this.idJefatura = idJefatura;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.grado = grado;
       this.dni = dni;
       this.profesion = profesion;
    }
   
    public BigDecimal getIdJefatura() {
        return this.idJefatura;
    }
    
    public void setIdJefatura(BigDecimal idJefatura) {
        this.idJefatura = idJefatura;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }




}


