package maping;
// Generated 30/09/2014 04:09:18 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * MovimientoInterno generated by hbm2java
 */
public class MovimientoInterno  implements java.io.Serializable {


     private int idMoviint;
     private TramiteDatos tramiteDatos;
     private Dependencia dependenciaByCodigo1;
     private Dependencia dependenciaByCodigo;
     private Indicador indicador;
     private int moviNumint;
     private Date fechaEnvint;
     private Date fechaIngrint;
     private String obsMovint;
     private String estadInt;
     private String estadoConfirmado;
     private String estadoDerivado;

    public MovimientoInterno() {
    }

	
    public MovimientoInterno(int idMoviint, int moviNumint, Date fechaEnvint) {
        this.idMoviint = idMoviint;
        this.moviNumint = moviNumint;
        this.fechaEnvint = fechaEnvint;
    }
    public MovimientoInterno(int idMoviint, TramiteDatos tramiteDatos, Dependencia dependenciaByCodigo1, Dependencia dependenciaByCodigo, Indicador indicador, int moviNumint, Date fechaEnvint, Date fechaIngrint, String obsMovint, String estadInt, String estadoConfirmado, String estadoDerivado) {
       this.idMoviint = idMoviint;
       this.tramiteDatos = tramiteDatos;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.indicador = indicador;
       this.moviNumint = moviNumint;
       this.fechaEnvint = fechaEnvint;
       this.fechaIngrint = fechaIngrint;
       this.obsMovint = obsMovint;
       this.estadInt = estadInt;
       this.estadoConfirmado = estadoConfirmado;
       this.estadoDerivado = estadoDerivado;
    }
   
    public int getIdMoviint() {
        return this.idMoviint;
    }
    
    public void setIdMoviint(int idMoviint) {
        this.idMoviint = idMoviint;
    }
    public TramiteDatos getTramiteDatos() {
        return this.tramiteDatos;
    }
    
    public void setTramiteDatos(TramiteDatos tramiteDatos) {
        this.tramiteDatos = tramiteDatos;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }
    public int getMoviNumint() {
        return this.moviNumint;
    }
    
    public void setMoviNumint(int moviNumint) {
        this.moviNumint = moviNumint;
    }
    public Date getFechaEnvint() {
        return this.fechaEnvint;
    }
    
    public void setFechaEnvint(Date fechaEnvint) {
        this.fechaEnvint = fechaEnvint;
    }
    public Date getFechaIngrint() {
        return this.fechaIngrint;
    }
    
    public void setFechaIngrint(Date fechaIngrint) {
        this.fechaIngrint = fechaIngrint;
    }
    public String getObsMovint() {
        return this.obsMovint;
    }
    
    public void setObsMovint(String obsMovint) {
        this.obsMovint = obsMovint;
    }
    public String getEstadInt() {
        return this.estadInt;
    }
    
    public void setEstadInt(String estadInt) {
        this.estadInt = estadInt;
    }
    public String getEstadoConfirmado() {
        return this.estadoConfirmado;
    }
    
    public void setEstadoConfirmado(String estadoConfirmado) {
        this.estadoConfirmado = estadoConfirmado;
    }
    public String getEstadoDerivado() {
        return this.estadoDerivado;
    }
    
    public void setEstadoDerivado(String estadoDerivado) {
        this.estadoDerivado = estadoDerivado;
    }




}


