package maping;
// Generated 17/04/2015 04:53:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Oficios generated by hbm2java
 */
public class Oficios  implements java.io.Serializable {


     private long idOficio;
     private TiposDocumentos tiposDocumentos;
     private TramiteDatos tramiteDatos;
     private Dependencia dependenciaByCodigo1;
     private Usuario usuario;
     private Dependencia dependenciaByCodigo;
     private String correlativoOficio;
     private Date fechaOficio;
     private String referenciaOficio;
     private String asuntoOficio;
     private String responsable;

    public Oficios() {
    }

	
    public Oficios(long idOficio) {
        this.idOficio = idOficio;
    }
    public Oficios(long idOficio, TiposDocumentos tiposDocumentos, TramiteDatos tramiteDatos, Dependencia dependenciaByCodigo1, Usuario usuario, Dependencia dependenciaByCodigo, String correlativoOficio, Date fechaOficio, String referenciaOficio, String asuntoOficio, String responsable) {
       this.idOficio = idOficio;
       this.tiposDocumentos = tiposDocumentos;
       this.tramiteDatos = tramiteDatos;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.usuario = usuario;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.correlativoOficio = correlativoOficio;
       this.fechaOficio = fechaOficio;
       this.referenciaOficio = referenciaOficio;
       this.asuntoOficio = asuntoOficio;
       this.responsable = responsable;
    }
   
    public long getIdOficio() {
        return this.idOficio;
    }
    
    public void setIdOficio(long idOficio) {
        this.idOficio = idOficio;
    }
    public TiposDocumentos getTiposDocumentos() {
        return this.tiposDocumentos;
    }
    
    public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
        this.tiposDocumentos = tiposDocumentos;
    }
    public TramiteDatos getTramiteDatos() {
        return this.tramiteDatos;
    }
    
    public void setTramiteDatos(TramiteDatos tramiteDatos) {
        this.tramiteDatos = tramiteDatos;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public String getCorrelativoOficio() {
        return this.correlativoOficio;
    }
    
    public void setCorrelativoOficio(String correlativoOficio) {
        this.correlativoOficio = correlativoOficio;
    }
    public Date getFechaOficio() {
        return this.fechaOficio;
    }
    
    public void setFechaOficio(Date fechaOficio) {
        this.fechaOficio = fechaOficio;
    }
    public String getReferenciaOficio() {
        return this.referenciaOficio;
    }
    
    public void setReferenciaOficio(String referenciaOficio) {
        this.referenciaOficio = referenciaOficio;
    }
    public String getAsuntoOficio() {
        return this.asuntoOficio;
    }
    
    public void setAsuntoOficio(String asuntoOficio) {
        this.asuntoOficio = asuntoOficio;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }




}


