package maping;
// Generated 23/10/2014 05:20:25 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OficCirc generated by hbm2java
 */
public class OficCirc  implements java.io.Serializable {


     private long idOfcirc;
     private Dependencia dependencia;
     private String correlaOficic;
     private String asunto;
     private Date fecha;
     private String firma;
     private String responsable;
     private Set<DetallOficcirc> detallOficcircs = new HashSet<DetallOficcirc>(0);

    public OficCirc() {
    }

	
    public OficCirc(long idOfcirc) {
        this.idOfcirc = idOfcirc;
    }
    public OficCirc(long idOfcirc, Dependencia dependencia, String correlaOficic, String asunto, Date fecha, String firma, String responsable, Set<DetallOficcirc> detallOficcircs) {
       this.idOfcirc = idOfcirc;
       this.dependencia = dependencia;
       this.correlaOficic = correlaOficic;
       this.asunto = asunto;
       this.fecha = fecha;
       this.firma = firma;
       this.responsable = responsable;
       this.detallOficcircs = detallOficcircs;
    }
   
    public long getIdOfcirc() {
        return this.idOfcirc;
    }
    
    public void setIdOfcirc(long idOfcirc) {
        this.idOfcirc = idOfcirc;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public String getCorrelaOficic() {
        return this.correlaOficic;
    }
    
    public void setCorrelaOficic(String correlaOficic) {
        this.correlaOficic = correlaOficic;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getFirma() {
        return this.firma;
    }
    
    public void setFirma(String firma) {
        this.firma = firma;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public Set<DetallOficcirc> getDetallOficcircs() {
        return this.detallOficcircs;
    }
    
    public void setDetallOficcircs(Set<DetallOficcirc> detallOficcircs) {
        this.detallOficcircs = detallOficcircs;
    }




}


