package maping;
// Generated 06/10/2014 08:55:07 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina  implements java.io.Serializable {


     private String idOficina;
     private String nombreOficina;
     private String siglas;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Oficina() {
    }

	
    public Oficina(String idOficina, String nombreOficina) {
        this.idOficina = idOficina;
        this.nombreOficina = nombreOficina;
    }

    public Oficina(String idOficina, String nombreOficina, String siglas) {
        this.idOficina = idOficina;
        this.nombreOficina = nombreOficina;
        this.siglas = siglas;
    }
    
   
    public String getIdOficina() {
        return this.idOficina;
    }
    
    public void setIdOficina(String idOficina) {
        this.idOficina = idOficina;
    }
    public String getNombreOficina() {
        return this.nombreOficina;
    }
    
    public void setNombreOficina(String nombreOficina) {
        this.nombreOficina = nombreOficina;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    public String getSiglas() {
        return siglas;
    }

    public void setSiglas(String siglas) {
        this.siglas = siglas;
    }
    
    


}


