package maping;
// Generated 30/09/2014 10:36:39 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina  implements java.io.Serializable {


     private String idOficina;
     private String nombreOficina;
     private String siglasofi;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Oficina() {
    }

	
    public Oficina(String idOficina, String nombreOficina) {
        this.idOficina = idOficina;
        this.nombreOficina = nombreOficina;
    }
    public Oficina(String idOficina, String nombreOficina, String siglasofi, Set<Usuario> usuarios) {
       this.idOficina = idOficina;
       this.nombreOficina = nombreOficina;
       this.siglasofi = siglasofi;
       this.usuarios = usuarios;
    }
   
    public String getIdOficina() {
        return this.idOficina;
    }
    
    public void setIdOficina(String idOficina) {
        this.idOficina = idOficina;
    }
    public String getNombreOficina() {
        return this.nombreOficina;
    }
    
    public void setNombreOficina(String nombreOficina) {
        this.nombreOficina = nombreOficina;
    }
    public String getSiglasofi() {
        return this.siglasofi;
    }
    
    public void setSiglasofi(String siglasofi) {
        this.siglasofi = siglasofi;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


