package maping;
// Generated 20/10/2014 11:41:07 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesion generated by hbm2java
 */
public class Profesion  implements java.io.Serializable {


     private BigDecimal idProfesion;
     private String profesionNombre;
     private String profesionSiglas;
     private Set<Jefatura> jefaturas = new HashSet<Jefatura>(0);

    public Profesion() {
    }

	
    public Profesion(BigDecimal idProfesion) {
        this.idProfesion = idProfesion;
    }
    public Profesion(BigDecimal idProfesion, String profesionNombre, String profesionSiglas, Set<Jefatura> jefaturas) {
       this.idProfesion = idProfesion;
       this.profesionNombre = profesionNombre;
       this.profesionSiglas = profesionSiglas;
       this.jefaturas = jefaturas;
    }
   
    public BigDecimal getIdProfesion() {
        return this.idProfesion;
    }
    
    public void setIdProfesion(BigDecimal idProfesion) {
        this.idProfesion = idProfesion;
    }
    public String getProfesionNombre() {
        return this.profesionNombre;
    }
    
    public void setProfesionNombre(String profesionNombre) {
        this.profesionNombre = profesionNombre;
    }
    public String getProfesionSiglas() {
        return this.profesionSiglas;
    }
    
    public void setProfesionSiglas(String profesionSiglas) {
        this.profesionSiglas = profesionSiglas;
    }
    public Set<Jefatura> getJefaturas() {
        return this.jefaturas;
    }
    
    public void setJefaturas(Set<Jefatura> jefaturas) {
        this.jefaturas = jefaturas;
    }




}


