package maping;
// Generated 23/10/2014 05:20:25 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Proveido generated by hbm2java
 */
public class Proveido  implements java.io.Serializable {


     private long correla;
     private Dependencia dependenciaByCodigo1;
     private DocusExtint docusExtint;
     private Dependencia dependenciaByCodigo;
     private String correlativod;
     private Date fecharegistro;
     private Date fechaenvio;

    public Proveido() {
    }

	
    public Proveido(long correla) {
        this.correla = correla;
    }
    public Proveido(long correla, Dependencia dependenciaByCodigo1, DocusExtint docusExtint, Dependencia dependenciaByCodigo, String correlativod, Date fecharegistro, Date fechaenvio) {
       this.correla = correla;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.docusExtint = docusExtint;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.correlativod = correlativod;
       this.fecharegistro = fecharegistro;
       this.fechaenvio = fechaenvio;
    }
   
    public long getCorrela() {
        return this.correla;
    }
    
    public void setCorrela(long correla) {
        this.correla = correla;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public DocusExtint getDocusExtint() {
        return this.docusExtint;
    }
    
    public void setDocusExtint(DocusExtint docusExtint) {
        this.docusExtint = docusExtint;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public String getCorrelativod() {
        return this.correlativod;
    }
    
    public void setCorrelativod(String correlativod) {
        this.correlativod = correlativod;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Date getFechaenvio() {
        return this.fechaenvio;
    }
    
    public void setFechaenvio(Date fechaenvio) {
        this.fechaenvio = fechaenvio;
    }




}


