package maping;
// Generated 09/10/2014 03:11:57 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Proveido generated by hbm2java
 */
public class Proveido  implements java.io.Serializable {


     private long correla;
     private Dependencia dependenciaByCodigo1;
     private DocusExtint docusExtint;
     private Dependencia dependenciaByCodigo;
     private Date fechareg;
     private Date fechaenvio;
     private String correlativod;

    public Proveido() {
    }

	
    public Proveido(long correla) {
        this.correla = correla;
    }
    public Proveido(long correla, Dependencia dependenciaByCodigo1, DocusExtint docusExtint, Dependencia dependenciaByCodigo, Date fechareg, Date fechaenvio, String correlativod) {
       this.correla = correla;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.docusExtint = docusExtint;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.fechareg = fechareg;
       this.fechaenvio = fechaenvio;
       this.correlativod=correlativod;
    }
   
    public long getCorrela() {
        return this.correla;
    }
    
    public void setCorrela(long correla) {
        this.correla = correla;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public DocusExtint getDocusExtint() {
        return this.docusExtint;
    }
    
    public void setDocusExtint(DocusExtint docusExtint) {
        this.docusExtint = docusExtint;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }
    public Date getFechaenvio() {
        return this.fechaenvio;
    }
    
    public void setFechaenvio(Date fechaenvio) {
        this.fechaenvio = fechaenvio;
    }

    public String getCorrelativod() {
        return correlativod;
    }

    public void setCorrelativod(String correlativod) {
        this.correlativod = correlativod;
    }




}


