package maping;
// Generated 17/04/2015 04:53:35 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * Temporalcargos generated by hbm2java
 */
public class Temporalcargos  implements java.io.Serializable {


     private BigDecimal idcargo;
     private String documento;
     private Date fecha;
     private String numexped;
     private String asunto;
     private String asignado;
     private String impreso;
     private String reimpreso;
     private String usu;
     private String destino;

    public Temporalcargos() {
    }

	
    public Temporalcargos(BigDecimal idcargo) {
        this.idcargo = idcargo;
    }
    public Temporalcargos(BigDecimal idcargo, String documento, Date fecha, String numexped, String asunto, String asignado, String impreso, String reimpreso, String usu, String destino) {
       this.idcargo = idcargo;
       this.documento = documento;
       this.fecha = fecha;
       this.numexped = numexped;
       this.asunto = asunto;
       this.asignado = asignado;
       this.impreso = impreso;
       this.reimpreso = reimpreso;
       this.usu = usu;
       this.destino = destino;
    }
   
    public BigDecimal getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(BigDecimal idcargo) {
        this.idcargo = idcargo;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNumexped() {
        return this.numexped;
    }
    
    public void setNumexped(String numexped) {
        this.numexped = numexped;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getAsignado() {
        return this.asignado;
    }
    
    public void setAsignado(String asignado) {
        this.asignado = asignado;
    }
    public String getImpreso() {
        return this.impreso;
    }
    
    public void setImpreso(String impreso) {
        this.impreso = impreso;
    }
    public String getReimpreso() {
        return this.reimpreso;
    }
    
    public void setReimpreso(String reimpreso) {
        this.reimpreso = reimpreso;
    }
    public String getUsu() {
        return this.usu;
    }
    
    public void setUsu(String usu) {
        this.usu = usu;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }




}


