package maping;
// Generated 17/04/2015 04:53:35 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * TemporalUser generated by hbm2java
 */
public class TemporalUser  implements java.io.Serializable {


     private BigDecimal idTempu;
     private String documento;
     private Date fecha;
     private String origenPrinc;
     private String impreso;
     private String reimpreso;
     private String documentoPrinc;
     private String tramNum;
     private String codigo;

    public TemporalUser() {
    }

	
    public TemporalUser(BigDecimal idTempu) {
        this.idTempu = idTempu;
    }
    public TemporalUser(BigDecimal idTempu, String documento, Date fecha, String origenPrinc, String impreso, String reimpreso, String documentoPrinc, String tramNum, String codigo) {
       this.idTempu = idTempu;
       this.documento = documento;
       this.fecha = fecha;
       this.origenPrinc = origenPrinc;
       this.impreso = impreso;
       this.reimpreso = reimpreso;
       this.documentoPrinc = documentoPrinc;
       this.tramNum = tramNum;
       this.codigo = codigo;
    }
   
    public BigDecimal getIdTempu() {
        return this.idTempu;
    }
    
    public void setIdTempu(BigDecimal idTempu) {
        this.idTempu = idTempu;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getOrigenPrinc() {
        return this.origenPrinc;
    }
    
    public void setOrigenPrinc(String origenPrinc) {
        this.origenPrinc = origenPrinc;
    }
    public String getImpreso() {
        return this.impreso;
    }
    
    public void setImpreso(String impreso) {
        this.impreso = impreso;
    }
    public String getReimpreso() {
        return this.reimpreso;
    }
    
    public void setReimpreso(String reimpreso) {
        this.reimpreso = reimpreso;
    }
    public String getDocumentoPrinc() {
        return this.documentoPrinc;
    }
    
    public void setDocumentoPrinc(String documentoPrinc) {
        this.documentoPrinc = documentoPrinc;
    }
    public String getTramNum() {
        return this.tramNum;
    }
    
    public void setTramNum(String tramNum) {
        this.tramNum = tramNum;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }




}


