package maping;
// Generated 23/10/2014 05:20:25 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Temporal generated by hbm2java
 */
public class TemporalCargos implements java.io.Serializable {

    private long idcargo;
    private String documento;
    private Date fecha;
    private String numexped;
    private String asunto;
    private String impreso;
    private String reimpreso;
    private String asignado;
    private String usu;
    private String destino;

    public TemporalCargos() {
    }

    public TemporalCargos(long idcargo) {
        this.idcargo = idcargo;
    }

    public TemporalCargos(long idcargo, String documento, Date fecha, String numexped, String asunto, String impreso, String reimpreso, String asignado, String usu, String destino) {
        this.idcargo = idcargo;
        this.documento = documento;
        this.fecha = fecha;
        this.numexped = numexped;
        this.asunto = asunto;
        this.impreso = impreso;
        this.reimpreso = reimpreso;
        this.asignado = asignado;
        this.usu = usu;
        this.destino = destino;
    }

    public long getIdcargo() {
        return idcargo;
    }

    public void setIdcargo(long idcargo) {
        this.idcargo = idcargo;
    }

    public String getDocumento() {
        return documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getNumexped() {
        return numexped;
    }

    public void setNumexped(String numexped) {
        this.numexped = numexped;
    }

    public String getAsunto() {
        return asunto;
    }

    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    public String getImpreso() {
        return impreso;
    }

    public void setImpreso(String impreso) {
        this.impreso = impreso;
    }

    public String getReimpreso() {
        return reimpreso;
    }

    public void setReimpreso(String reimpreso) {
        this.reimpreso = reimpreso;
    }

    public String getAsignado() {
        return asignado;
    }

    public void setAsignado(String asignado) {
        this.asignado = asignado;
    }

    public String getUsu() {
        return usu;
    }

    public void setUsu(String usu) {
        this.usu = usu;
    }

    public String getDestino() {
        return destino;
    }

    public void setDestino(String destino) {
        this.destino = destino;
    }

}
