package maping;
// Generated 17/04/2015 04:53:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TemporalDi generated by hbm2java
 */
public class TemporalDi  implements java.io.Serializable {


     private long idTemp;
     private String nombDocu;
     private Date fechaReg;
     private String tramNum;
     private String usuario;
     private String asunto;
     private String reimpreso;
     private String impreso;

    public TemporalDi() {
    }

	
    public TemporalDi(long idTemp) {
        this.idTemp = idTemp;
    }
    public TemporalDi(long idTemp, String nombDocu, Date fechaReg, String tramNum, String usuario, String asunto, String reimpreso, String impreso) {
       this.idTemp = idTemp;
       this.nombDocu = nombDocu;
       this.fechaReg = fechaReg;
       this.tramNum = tramNum;
       this.usuario = usuario;
       this.asunto = asunto;
       this.reimpreso = reimpreso;
       this.impreso = impreso;
    }
   
    public long getIdTemp() {
        return this.idTemp;
    }
    
    public void setIdTemp(long idTemp) {
        this.idTemp = idTemp;
    }
    public String getNombDocu() {
        return this.nombDocu;
    }
    
    public void setNombDocu(String nombDocu) {
        this.nombDocu = nombDocu;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public String getTramNum() {
        return this.tramNum;
    }
    
    public void setTramNum(String tramNum) {
        this.tramNum = tramNum;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getReimpreso() {
        return this.reimpreso;
    }
    
    public void setReimpreso(String reimpreso) {
        this.reimpreso = reimpreso;
    }

    public String getImpreso() {
        return impreso;
    }

    public void setImpreso(String impreso) {
        this.impreso = impreso;
    }




}


