package maping;
// Generated 05/11/2014 09:54:41 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TiposDocumentos generated by hbm2java
 */
public class TiposDocumentos  implements java.io.Serializable {


     private BigDecimal idDocumento;
     private String nombreDocu;
     private String flag;
     private Set<DetallOficcirc> detallOficcircs = new HashSet<DetallOficcirc>(0);

    public TiposDocumentos() {
    }

	
    public TiposDocumentos(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }
    public TiposDocumentos(BigDecimal idDocumento, String nombreDocu, String flag, Set<DetallOficcirc> detallOficcircs) {
       this.idDocumento = idDocumento;
       this.nombreDocu = nombreDocu;
       this.flag = flag;
       this.detallOficcircs = detallOficcircs;
    }
   
    public BigDecimal getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }
    public String getNombreDocu() {
        return this.nombreDocu;
    }
    
    public void setNombreDocu(String nombreDocu) {
        this.nombreDocu = nombreDocu;
    }
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }
    public Set<DetallOficcirc> getDetallOficcircs() {
        return this.detallOficcircs;
    }
    
    public void setDetallOficcircs(Set<DetallOficcirc> detallOficcircs) {
        this.detallOficcircs = detallOficcircs;
    }




}


