package maping;
// Generated 15/12/2014 11:44:57 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TiposDocumentos generated by hbm2java
 */
public class TiposDocumentos implements java.io.Serializable {

    private BigDecimal idDocumento;
    private String nombreDocu;
    private String flag;
    private Set<DetallOficcirc> detallOficcircs = new HashSet<DetallOficcirc>(0);
    private Set<Constancias> constanciases = new HashSet<Constancias>(0);
    private Set<DocusInternos> docusInternoses = new HashSet<DocusInternos>(0);
    private Set<Oficios> oficioses = new HashSet<Oficios>(0);
    private Set<DocumentosOfiint> documentosOfiints = new HashSet<DocumentosOfiint>(0);
    private Set<DocusExtint> docusExtints = new HashSet<DocusExtint>(0);
    private Set<OficCirc> oficCirc = new HashSet<OficCirc>(0);

    public TiposDocumentos() {
    }

    public TiposDocumentos(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }

    public TiposDocumentos(BigDecimal idDocumento, String nombreDocu, String flag, Set<DetallOficcirc> detallOficcircs, Set<Constancias> constanciases, Set<DocusInternos> docusInternoses, Set<Oficios> oficioses, Set<DocumentosOfiint> documentosOfiints, Set<DocusExtint> docusExtints, Set<OficCirc> oficCirc) {
        this.idDocumento = idDocumento;
        this.nombreDocu = nombreDocu;
        this.flag = flag;
        this.detallOficcircs = detallOficcircs;
        this.constanciases = constanciases;
        this.docusInternoses = docusInternoses;
        this.oficioses = oficioses;
        this.documentosOfiints = documentosOfiints;
        this.docusExtints = docusExtints;
        this.oficCirc = oficCirc;
    }

    public BigDecimal getIdDocumento() {
        return this.idDocumento;
    }

    public void setIdDocumento(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }

    public String getNombreDocu() {
        return this.nombreDocu;
    }

    public void setNombreDocu(String nombreDocu) {
        this.nombreDocu = nombreDocu;
    }

    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public Set<DetallOficcirc> getDetallOficcircs() {
        return this.detallOficcircs;
    }

    public void setDetallOficcircs(Set<DetallOficcirc> detallOficcircs) {
        this.detallOficcircs = detallOficcircs;
    }

    public Set<Constancias> getConstanciases() {
        return this.constanciases;
    }

    public void setConstanciases(Set<Constancias> constanciases) {
        this.constanciases = constanciases;
    }

    public Set<DocusInternos> getDocusInternoses() {
        return this.docusInternoses;
    }

    public void setDocusInternoses(Set<DocusInternos> docusInternoses) {
        this.docusInternoses = docusInternoses;
    }

    public Set<Oficios> getOficioses() {
        return this.oficioses;
    }

    public void setOficioses(Set<Oficios> oficioses) {
        this.oficioses = oficioses;
    }

    public Set<DocumentosOfiint> getDocumentosOfiints() {
        return this.documentosOfiints;
    }

    public void setDocumentosOfiints(Set<DocumentosOfiint> documentosOfiints) {
        this.documentosOfiints = documentosOfiints;
    }

    public Set<DocusExtint> getDocusExtints() {
        return this.docusExtints;
    }

    public void setDocusExtints(Set<DocusExtint> docusExtints) {
        this.docusExtints = docusExtints;
    }

    public Set<OficCirc> getOficCirc() {
        return oficCirc;
    }

    public void setOficCirc(Set<OficCirc> oficCirc) {
        this.oficCirc = oficCirc;
    }

}
