package maping;
// Generated 17/04/2015 04:53:35 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TiposDocumentos generated by hbm2java
 */
public class TiposDocumentos  implements java.io.Serializable {


     private BigDecimal idDocumento;
     private String nombreDocu;
     private String flag;
     private String flag2;
     private Set<DocusExtint> docusExtints = new HashSet<DocusExtint>(0);
     private Set<OficCirc> oficCircs = new HashSet<OficCirc>(0);
     private Set<DetallOficcirc> detallOficcircs = new HashSet<DetallOficcirc>(0);
     private Set<Oficios> oficioses = new HashSet<Oficios>(0);
     private Set<DocusInternos> docusInternoses = new HashSet<DocusInternos>(0);
     private Set<Constancias> constanciases = new HashSet<Constancias>(0);

    public TiposDocumentos() {
    }

	
    public TiposDocumentos(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }
    public TiposDocumentos(BigDecimal idDocumento, String nombreDocu, String flag, String flag2, Set<DocusExtint> docusExtints, Set<OficCirc> oficCircs, Set<DetallOficcirc> detallOficcircs, Set<Oficios> oficioses, Set<DocusInternos> docusInternoses, Set<Constancias> constanciases) {
       this.idDocumento = idDocumento;
       this.nombreDocu = nombreDocu;
       this.flag = flag;
       this.flag2 = flag2;
       this.docusExtints = docusExtints;
       this.oficCircs = oficCircs;
       this.detallOficcircs = detallOficcircs;
       this.oficioses = oficioses;
       this.docusInternoses = docusInternoses;
       this.constanciases = constanciases;
    }
   
    public BigDecimal getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }
    public String getNombreDocu() {
        return this.nombreDocu;
    }
    
    public void setNombreDocu(String nombreDocu) {
        this.nombreDocu = nombreDocu;
    }
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    public Set<DocusExtint> getDocusExtints() {
        return this.docusExtints;
    }
    
    public void setDocusExtints(Set<DocusExtint> docusExtints) {
        this.docusExtints = docusExtints;
    }
    public Set<OficCirc> getOficCircs() {
        return this.oficCircs;
    }
    
    public void setOficCircs(Set<OficCirc> oficCircs) {
        this.oficCircs = oficCircs;
    }
    public Set<DetallOficcirc> getDetallOficcircs() {
        return this.detallOficcircs;
    }
    
    public void setDetallOficcircs(Set<DetallOficcirc> detallOficcircs) {
        this.detallOficcircs = detallOficcircs;
    }
    public Set<Oficios> getOficioses() {
        return this.oficioses;
    }
    
    public void setOficioses(Set<Oficios> oficioses) {
        this.oficioses = oficioses;
    }
    public Set<DocusInternos> getDocusInternoses() {
        return this.docusInternoses;
    }
    
    public void setDocusInternoses(Set<DocusInternos> docusInternoses) {
        this.docusInternoses = docusInternoses;
    }
    public Set<Constancias> getConstanciases() {
        return this.constanciases;
    }
    
    public void setConstanciases(Set<Constancias> constanciases) {
        this.constanciases = constanciases;
    }




}


