package maping;
// Generated 02/09/2014 12:28:10 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * TramiteMovimiento generated by hbm2java
 */
public class TramiteMovimiento  implements java.io.Serializable {


     private BigDecimal idMovi;
     private TramiteDatos tramiteDatos;
     private Dependencia dependenciaByCodigo1;
     private Dependencia dependenciaByCodigo;
     private Indicador indicador;
     private Short moviNum;
     private Date fechaEnvio;
     private Date fechaIngr;
     private String moviObs;
     private String estaNombre;

    public TramiteMovimiento() {
    }

	
    public TramiteMovimiento(BigDecimal idMovi) {
        this.idMovi = idMovi;
    }
    public TramiteMovimiento(BigDecimal idMovi, TramiteDatos tramiteDatos, Dependencia dependenciaByCodigo1, Dependencia dependenciaByCodigo, Indicador indicador, Short moviNum, Date fechaEnvio, Date fechaIngr, String moviObs, String estaNombre) {
       this.idMovi = idMovi;
       this.tramiteDatos = tramiteDatos;
       this.dependenciaByCodigo1 = dependenciaByCodigo1;
       this.dependenciaByCodigo = dependenciaByCodigo;
       this.indicador = indicador;
       this.moviNum = moviNum;
       this.fechaEnvio = fechaEnvio;
       this.fechaIngr = fechaIngr;
       this.moviObs = moviObs;
       this.estaNombre = estaNombre;
    }
   
    public BigDecimal getIdMovi() {
        return this.idMovi;
    }
    
    public void setIdMovi(BigDecimal idMovi) {
        this.idMovi = idMovi;
    }
    public TramiteDatos getTramiteDatos() {
        return this.tramiteDatos;
    }
    
    public void setTramiteDatos(TramiteDatos tramiteDatos) {
        this.tramiteDatos = tramiteDatos;
    }
    public Dependencia getDependenciaByCodigo1() {
        return this.dependenciaByCodigo1;
    }
    
    public void setDependenciaByCodigo1(Dependencia dependenciaByCodigo1) {
        this.dependenciaByCodigo1 = dependenciaByCodigo1;
    }
    public Dependencia getDependenciaByCodigo() {
        return this.dependenciaByCodigo;
    }
    
    public void setDependenciaByCodigo(Dependencia dependenciaByCodigo) {
        this.dependenciaByCodigo = dependenciaByCodigo;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }
    public Short getMoviNum() {
        return this.moviNum;
    }
    
    public void setMoviNum(Short moviNum) {
        this.moviNum = moviNum;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public Date getFechaIngr() {
        return this.fechaIngr;
    }
    
    public void setFechaIngr(Date fechaIngr) {
        this.fechaIngr = fechaIngr;
    }
    public String getMoviObs() {
        return this.moviObs;
    }
    
    public void setMoviObs(String moviObs) {
        this.moviObs = moviObs;
    }
    public String getEstaNombre() {
        return this.estaNombre;
    }
    
    public void setEstaNombre(String estaNombre) {
        this.estaNombre = estaNombre;
    }




}


