package maping;
// Generated 15/09/2014 10:37:29 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TramiteDatos generated by hbm2java
 */
public class TramiteDatos  implements java.io.Serializable {


     private String tramNum;
     private Usuario usuario;
     private Dependencia dependencia;
     private Date tramFecha;
     private String tramObs;
     private String estaDescrip;
     private Set<MovimientoInterno> movimientoInternos = new HashSet<MovimientoInterno>(0);
     private Set<DocusInternos> docusInternoses = new HashSet<DocusInternos>(0);
     private Set<TramiteMovimiento> tramiteMovimientos = new HashSet<TramiteMovimiento>(0);
     private Set<TipoDocu> tipoDocus = new HashSet<TipoDocu>(0);

    public TramiteDatos() {
    }

	
    public TramiteDatos(String tramNum, Date tramFecha) {
        this.tramNum = tramNum;
        this.tramFecha = tramFecha;
    }
    public TramiteDatos(String tramNum, Usuario usuario, Dependencia dependencia, Date tramFecha, String tramObs, String estaDescrip, Set<MovimientoInterno> movimientoInternos, Set<DocusInternos> docusInternoses, Set<TramiteMovimiento> tramiteMovimientos, Set<TipoDocu> tipoDocus) {
       this.tramNum = tramNum;
       this.usuario = usuario;
       this.dependencia = dependencia;
       this.tramFecha = tramFecha;
       this.tramObs = tramObs;
       this.estaDescrip = estaDescrip;
       this.movimientoInternos = movimientoInternos;
       this.docusInternoses = docusInternoses;
       this.tramiteMovimientos = tramiteMovimientos;
       this.tipoDocus = tipoDocus;
    }
   
    public String getTramNum() {
        return this.tramNum;
    }
    
    public void setTramNum(String tramNum) {
        this.tramNum = tramNum;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public Date getTramFecha() {
        return this.tramFecha;
    }
    
    public void setTramFecha(Date tramFecha) {
        this.tramFecha = tramFecha;
    }
    public String getTramObs() {
        return this.tramObs;
    }
    
    public void setTramObs(String tramObs) {
        this.tramObs = tramObs;
    }
    public String getEstaDescrip() {
        return this.estaDescrip;
    }
    
    public void setEstaDescrip(String estaDescrip) {
        this.estaDescrip = estaDescrip;
    }
    public Set<MovimientoInterno> getMovimientoInternos() {
        return this.movimientoInternos;
    }
    
    public void setMovimientoInternos(Set<MovimientoInterno> movimientoInternos) {
        this.movimientoInternos = movimientoInternos;
    }
    public Set<DocusInternos> getDocusInternoses() {
        return this.docusInternoses;
    }
    
    public void setDocusInternoses(Set<DocusInternos> docusInternoses) {
        this.docusInternoses = docusInternoses;
    }
    public Set<TramiteMovimiento> getTramiteMovimientos() {
        return this.tramiteMovimientos;
    }
    
    public void setTramiteMovimientos(Set<TramiteMovimiento> tramiteMovimientos) {
        this.tramiteMovimientos = tramiteMovimientos;
    }
    public Set<TipoDocu> getTipoDocus() {
        return this.tipoDocus;
    }
    
    public void setTipoDocus(Set<TipoDocu> tipoDocus) {
        this.tipoDocus = tipoDocus;
    }




}


