package maping;
// Generated 17/04/2015 04:53:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TramiteDatosId generated by hbm2java
 */
public class TramiteDatosId  implements java.io.Serializable {


     private String tramNum;
     private Date tramFecha;

    public TramiteDatosId() {
    }

    public TramiteDatosId(String tramNum, Date tramFecha) {
       this.tramNum = tramNum;
       this.tramFecha = tramFecha;
    }
   
    public String getTramNum() {
        return this.tramNum;
    }
    
    public void setTramNum(String tramNum) {
        this.tramNum = tramNum;
    }
    public Date getTramFecha() {
        return this.tramFecha;
    }
    
    public void setTramFecha(Date tramFecha) {
        this.tramFecha = tramFecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TramiteDatosId) ) return false;
		 TramiteDatosId castOther = ( TramiteDatosId ) other; 
         
		 return ( (this.getTramNum()==castOther.getTramNum()) || ( this.getTramNum()!=null && castOther.getTramNum()!=null && this.getTramNum().equals(castOther.getTramNum()) ) )
 && ( (this.getTramFecha()==castOther.getTramFecha()) || ( this.getTramFecha()!=null && castOther.getTramFecha()!=null && this.getTramFecha().equals(castOther.getTramFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTramNum() == null ? 0 : this.getTramNum().hashCode() );
         result = 37 * result + ( getTramFecha() == null ? 0 : this.getTramFecha().hashCode() );
         return result;
   }   


}


