package maping;
// Generated 02/10/2014 12:28:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usu;
     private Oficina oficina;
     private String usuNombre;
     private String clave;
     private String estado;
     private Set<DocusExtint> docusExtints = new HashSet<DocusExtint>(0);
     private Set<Jefatura> jefaturas = new HashSet<Jefatura>(0);
     private Set<TramiteDatos> tramiteDatoses = new HashSet<TramiteDatos>(0);
     private Set<DocusInternos> docusInternoses = new HashSet<DocusInternos>(0);

    public Usuario() {
    }

	
    public Usuario(String usu, String usuNombre, String clave) {
        this.usu = usu;
        this.usuNombre = usuNombre;
        this.clave = clave;
    }
    public Usuario(String usu, Oficina oficina, String usuNombre, String clave, String estado, Set<DocusExtint> docusExtints, Set<Jefatura> jefaturas, Set<TramiteDatos> tramiteDatoses, Set<DocusInternos> docusInternoses) {
       this.usu = usu;
       this.oficina = oficina;
       this.usuNombre = usuNombre;
       this.clave = clave;
       this.estado = estado;
       this.docusExtints = docusExtints;
       this.jefaturas = jefaturas;
       this.tramiteDatoses = tramiteDatoses;
       this.docusInternoses = docusInternoses;
    }
   
    public String getUsu() {
        return this.usu;
    }
    
    public void setUsu(String usu) {
        this.usu = usu;
    }
    public Oficina getOficina() {
        return this.oficina;
    }
    
    public void setOficina(Oficina oficina) {
        this.oficina = oficina;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<DocusExtint> getDocusExtints() {
        return this.docusExtints;
    }
    
    public void setDocusExtints(Set<DocusExtint> docusExtints) {
        this.docusExtints = docusExtints;
    }
    public Set<Jefatura> getJefaturas() {
        return this.jefaturas;
    }
    
    public void setJefaturas(Set<Jefatura> jefaturas) {
        this.jefaturas = jefaturas;
    }
    public Set<TramiteDatos> getTramiteDatoses() {
        return this.tramiteDatoses;
    }
    
    public void setTramiteDatoses(Set<TramiteDatos> tramiteDatoses) {
        this.tramiteDatoses = tramiteDatoses;
    }
    public Set<DocusInternos> getDocusInternoses() {
        return this.docusInternoses;
    }
    
    public void setDocusInternoses(Set<DocusInternos> docusInternoses) {
        this.docusInternoses = docusInternoses;
    }




}


