package maping;
// Generated 22/09/2014 05:15:43 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usu;
     private Oficina oficina;
     private String usuNombre;
     private String clave;
     private Set<TramiteDatos> tramiteDatoses = new HashSet<TramiteDatos>(0);

    public Usuario() {
    }

	
    public Usuario(String usu, String usuNombre, String clave) {
        this.usu = usu;
        this.usuNombre = usuNombre;
        this.clave = clave;
    }
    public Usuario(String usu, Oficina oficina, String usuNombre, String clave, Set<TramiteDatos> tramiteDatoses) {
       this.usu = usu;
       this.oficina = oficina;
       this.usuNombre = usuNombre;
       this.clave = clave;
       this.tramiteDatoses = tramiteDatoses;
    }
   
    public String getUsu() {
        return this.usu;
    }
    
    public void setUsu(String usu) {
        this.usu = usu;
    }
    public Oficina getOficina() {
        return this.oficina;
    }
    
    public void setOficina(Oficina oficina) {
        this.oficina = oficina;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set<TramiteDatos> getTramiteDatoses() {
        return this.tramiteDatoses;
    }
    
    public void setTramiteDatoses(Set<TramiteDatos> tramiteDatoses) {
        this.tramiteDatoses = tramiteDatoses;
    }




}


